import {firebaseConfig} from '../firebase-config.js';
import {getFirebaseContext,isFirebaseConfigured} from '../assets/js/firebase-catalog.js';

const qs=(selector,root=document)=>root.querySelector(selector);
const qsa=(selector,root=document)=>[...root.querySelectorAll(selector)];
const state={ctx:null,config:null,categories:[],products:[],demo:false,currentId:null,currentCategoryId:null,drag:null,needsCatalogUpgrade:false};
const setup=qs('[data-setup]'),login=qs('[data-login]'),dashboard=qs('[data-dashboard]');
const productEditor=qs('[data-product-editor]'),productForm=qs('[data-product-form]');
const categoryEditor=qs('[data-category-editor]'),categoryForm=qs('[data-category-form]');
const appearanceForm=qs('[data-appearance-form]');
const serviceForm=qs('[data-service-form]');
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0);
const slug=value=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const byOrder=(a,b)=>(a.order??9999)-(b.order??9999)||a.name.localeCompare(b.name,'pt-BR');
const pinkTheme={primary:'#ff5f98',accent:'#ff8bb4',bg:'#fffafb',surface:'#ffffff',text:'#572332',muted:'#8b6671',line:'#f3d9e2'};
const weekDays=['Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado','Domingo'];

async function loadLocal(){const [config,categories,products]=await Promise.all(['../data/config.json','../data/categories.json','../data/products.json'].map(url=>fetch(url,{cache:'no-store'}).then(r=>r.json())));state.config=config;state.categories=categories.map((c,i)=>({...c,order:c.order??i}));state.products=products.map((p,i)=>({...p,order:p.order??i}))}
function show(view){[setup,login,dashboard].forEach(item=>item.hidden=item!==view)}
function message(target,text='',success=false){target.textContent=text;target.classList.toggle('success',success)}

function variantRow(variant={}){const row=qs('#variant-row-template').content.firstElementChild.cloneNode(true);qs('[data-variant-label]',row).value=variant.label||'';qs('[data-variant-price]',row).value=variant.price??'';qs('[data-remove-variant]',row).addEventListener('click',()=>row.remove());return row}
function setVariants(variants=[]){qs('[data-variant-rows]').replaceChildren(...variants.map(variantRow))}
function getVariants(){return qsa('.variant-row').map(row=>({label:qs('[data-variant-label]',row).value.trim(),price:Number(qs('[data-variant-price]',row).value)})).filter(item=>item.label).map((item,index)=>({id:slug(item.label)||`variacao-${index+1}`,...item}))}

function populateCategoryControls(){const active=state.categories.slice().sort(byOrder);productForm.elements.categoryId.replaceChildren(...active.map(category=>new Option(category.name,category.id)));const filter=qs('[data-category-filter]');const current=filter.value;filter.innerHTML='<option value="">Todas as categorias</option>';active.forEach(category=>filter.add(new Option(category.name,category.id)));filter.value=current}
function openProductEditor(product=null){state.currentId=product?.id||null;productForm.reset();qs('[data-editor-title]').textContent=product?'Editar produto':'Novo produto';populateCategoryControls();productForm.elements.name.value=product?.name||'';productForm.elements.categoryId.value=product?.categoryId||state.categories.slice().sort(byOrder)[0]?.id||'';productForm.elements.description.value=product?.description||'';productForm.elements.price.value=product?.price??'';productForm.elements.tag.value=product?.tag||'';productForm.elements.image.value=product?.image||'';productForm.elements.available.checked=product?.available!==false;setVariants(product?.variants||[]);message(qs('[data-editor-message]'));productEditor.showModal()}
function openCategoryEditor(category=null){state.currentCategoryId=category?.id||null;categoryForm.reset();qs('[data-category-editor-title]').textContent=category?'Editar categoria':'Nova categoria';categoryForm.elements.name.value=category?.name||'';categoryForm.elements.description.value=category?.description||'';categoryForm.elements.enabled.checked=category?.enabled!==false;message(qs('[data-category-message]'));categoryEditor.showModal()}

async function persist(collectionName,item){if(state.demo)return;const {doc,setDoc}=state.ctx.firestoreSdk;await setDoc(doc(state.ctx.db,'stores',state.ctx.storeId,collectionName,item.id),item)}
async function removeDoc(collectionName,id){if(state.demo)return;const {doc,deleteDoc}=state.ctx.firestoreSdk;await deleteDoc(doc(state.ctx.db,'stores',state.ctx.storeId,collectionName,id))}
async function persistOrder(collectionName,items){items.forEach((item,index)=>item.order=index);if(state.demo)return;const {doc,writeBatch}=state.ctx.firestoreSdk;const batch=writeBatch(state.ctx.db);items.forEach(item=>batch.update(doc(state.ctx.db,'stores',state.ctx.storeId,collectionName,item.id),{order:item.order}));await batch.commit()}

function dragEvents(article,type){article.draggable=true;article.addEventListener('dragstart',event=>{state.drag={type,id:article.dataset.id};article.classList.add('dragging');event.dataTransfer.effectAllowed='move'});article.addEventListener('dragend',()=>{state.drag=null;article.classList.remove('dragging');qsa('.drag-over').forEach(item=>item.classList.remove('drag-over'))});article.addEventListener('dragover',event=>{if(state.drag?.type!==type||state.drag.id===article.dataset.id)return;event.preventDefault();article.classList.add('drag-over')});article.addEventListener('dragleave',()=>article.classList.remove('drag-over'));article.addEventListener('drop',async event=>{event.preventDefault();article.classList.remove('drag-over');if(!state.drag||state.drag.type!==type)return;const items=type==='product'?state.products:state.categories;const from=items.findIndex(item=>item.id===state.drag.id);const to=items.findIndex(item=>item.id===article.dataset.id);if(from<0||to<0||from===to)return;const [moved]=items.splice(from,1);items.splice(to,0,moved);await persistOrder(type==='product'?'products':'categories',items);type==='product'?renderProducts():renderCategories()})}
async function moveItem(type,id,direction){const items=type==='product'?state.products:state.categories;items.sort(byOrder);const index=items.findIndex(item=>item.id===id);const target=index+direction;if(index<0||target<0||target>=items.length)return;[items[index],items[target]]=[items[target],items[index]];await persistOrder(type==='product'?'products':'categories',items);type==='product'?renderProducts():renderCategories()}

function actionButton(label,title,onClick,className=''){const button=document.createElement('button');button.type='button';button.textContent=label;button.title=title;button.setAttribute('aria-label',title);button.className=className;button.addEventListener('click',onClick);return button}
function renderProducts(){const box=qs('[data-admin-products]');box.replaceChildren();qs('[data-product-count]').textContent=state.products.length;const term=qs('[data-product-search]').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const categoryFilter=qs('[data-category-filter]').value;const filtered=state.products.slice().sort(byOrder).filter(product=>(!categoryFilter||product.categoryId===categoryFilter)&&(!term||`${product.name} ${product.description||''}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(term)));filtered.forEach(product=>{const article=document.createElement('article');article.className=`admin-product${product.available===false?' inactive':''}`;article.dataset.id=product.id;const handle=document.createElement('span');handle.className='drag-handle';handle.textContent='⋮⋮';handle.title='Arraste para ordenar';const info=document.createElement('div');info.className='item-info';info.innerHTML=`<h3></h3><p></p><strong></strong>`;qs('h3',info).textContent=product.name;qs('p',info).textContent=`${state.categories.find(c=>c.id===product.categoryId)?.name||'Sem categoria'} · ${product.available===false?'Inativo':'Ativo'}`;const prices=product.variants?.map(v=>Number(v.price))||[];qs('strong',info).textContent=money(prices.length?Math.min(...prices):product.price);const actions=document.createElement('div');actions.className='item-actions';actions.append(actionButton('↑','Mover para cima',()=>moveItem('product',product.id,-1)),actionButton('↓','Mover para baixo',()=>moveItem('product',product.id,1)),actionButton('✎','Editar produto',()=>openProductEditor(product)),actionButton(product.available===false?'○':'●',product.available===false?'Ativar produto':'Inativar produto',()=>toggleProduct(product)),actionButton('×','Remover produto',()=>deleteProduct(product),'danger'));article.append(handle,info,actions);if(!term&&!categoryFilter)dragEvents(article,'product');else article.draggable=false;box.append(article)});if(!filtered.length)box.innerHTML='<p class="empty-list">Nenhum produto encontrado.</p>'}

function renderCategories(){const box=qs('[data-admin-categories]');box.replaceChildren();qs('[data-category-count]').textContent=state.categories.length;state.categories.slice().sort(byOrder).forEach(category=>{const count=state.products.filter(product=>product.categoryId===category.id).length;const article=document.createElement('article');article.className=`admin-category${category.enabled===false?' inactive':''}`;article.dataset.id=category.id;const handle=document.createElement('span');handle.className='drag-handle';handle.textContent='⋮⋮';const info=document.createElement('div');info.className='item-info';info.innerHTML='<h3></h3><p></p>';qs('h3',info).textContent=category.name;qs('p',info).textContent=`${count} ${count===1?'produto':'produtos'} · ${category.enabled===false?'Inativa':'Ativa'}`;const actions=document.createElement('div');actions.className='item-actions';actions.append(actionButton('↑','Mover para cima',()=>moveItem('category',category.id,-1)),actionButton('↓','Mover para baixo',()=>moveItem('category',category.id,1)),actionButton('✎','Editar categoria',()=>openCategoryEditor(category)),actionButton(category.enabled===false?'○':'●',category.enabled===false?'Ativar categoria':'Inativar categoria',()=>toggleCategory(category)),actionButton('×','Remover categoria',()=>deleteCategory(category),'danger'));article.append(handle,info,actions);dragEvents(article,'category');box.append(article)})}

async function toggleProduct(product){const updated={...product,available:product.available===false};await persist('products',updated);state.products[state.products.findIndex(item=>item.id===product.id)]=updated;renderProducts()}
async function deleteProduct(product){if(!confirm(`Remover “${product.name}”?`))return;await removeDoc('products',product.id);state.products=state.products.filter(item=>item.id!==product.id);await persistOrder('products',state.products);renderProducts();renderCategories()}
async function toggleCategory(category){const updated={...category,enabled:category.enabled===false};await persist('categories',updated);state.categories[state.categories.findIndex(item=>item.id===category.id)]=updated;renderCategories();populateCategoryControls()}
async function deleteCategory(category){const count=state.products.filter(product=>product.categoryId===category.id).length;if(count){alert(`Esta categoria possui ${count} produto(s). Mova-os para outra categoria antes de removê-la.`);return}if(!confirm(`Remover a categoria “${category.name}”?`))return;await removeDoc('categories',category.id);state.categories=state.categories.filter(item=>item.id!==category.id);await persistOrder('categories',state.categories);renderCategories();populateCategoryControls()}

productForm.addEventListener('submit',async event=>{event.preventDefault();const submit=event.submitter;submit.disabled=true;try{const existing=state.products.find(item=>item.id===state.currentId)||{};const name=productForm.elements.name.value.trim();const id=state.currentId||slug(name)||crypto.randomUUID();const variants=getVariants();const product={...existing,id,name,categoryId:productForm.elements.categoryId.value,description:productForm.elements.description.value.trim(),price:Number(productForm.elements.price.value)||0,tag:productForm.elements.tag.value.trim(),image:productForm.elements.image.value.trim(),available:productForm.elements.available.checked,order:existing.order??state.products.length};if(variants.length)product.variants=variants;else delete product.variants;await persist('products',product);const index=state.products.findIndex(item=>item.id===id);if(index>=0)state.products[index]=product;else state.products.push(product);renderProducts();renderCategories();productEditor.close()}catch(error){message(qs('[data-editor-message]'),`Não foi possível salvar: ${error.message}`)}finally{submit.disabled=false}});
categoryForm.addEventListener('submit',async event=>{event.preventDefault();const submit=event.submitter;submit.disabled=true;try{const existing=state.categories.find(item=>item.id===state.currentCategoryId)||{};const name=categoryForm.elements.name.value.trim();const id=state.currentCategoryId||slug(name)||crypto.randomUUID();if(!state.currentCategoryId&&state.categories.some(item=>item.id===id))throw new Error('Já existe uma categoria com esse nome.');const category={...existing,id,name,description:categoryForm.elements.description.value.trim(),enabled:categoryForm.elements.enabled.checked,order:existing.order??state.categories.length};await persist('categories',category);const index=state.categories.findIndex(item=>item.id===id);if(index>=0)state.categories[index]=category;else state.categories.push(category);renderCategories();populateCategoryControls();renderProducts();categoryEditor.close()}catch(error){message(qs('[data-category-message]'),`Não foi possível salvar: ${error.message}`)}finally{submit.disabled=false}});

async function setStoreOpen(open){state.config.business.open=open;qs('[data-store-status]').textContent=open?'Aberto':'Fechado';if(!state.demo){const {doc,setDoc}=state.ctx.firestoreSdk;await setDoc(doc(state.ctx.db,'stores',state.ctx.storeId),{business:{...state.config.business,open}},{merge:true})}}
qs('[data-store-open]').addEventListener('change',event=>setStoreOpen(event.target.checked).catch(error=>{event.target.checked=!event.target.checked;alert(`Não foi possível alterar o status: ${error.message}`)}));

function fillAppearance(){const business=state.config.business||{};appearanceForm.elements.businessName.value=business.name||'';appearanceForm.elements.businessType.value=business.type||'';appearanceForm.elements.businessDescription.value=business.description||'';const colors={...pinkTheme,...state.config.theme?.colors};Object.keys(pinkTheme).filter(key=>key!=='line').forEach(key=>{appearanceForm.elements[key].value=colors[key];appearanceForm.elements[`${key}Hex`].value=colors[key]});updateThemePreview()}
function updateThemePreview(){const preview=qs('[data-theme-preview]');const colors={};Object.keys(pinkTheme).filter(key=>key!=='line').forEach(key=>colors[key]=appearanceForm.elements[key].value);preview.style.cssText=`--preview-primary:${colors.primary};--preview-accent:${colors.accent};--preview-bg:${colors.bg};--preview-surface:${colors.surface};--preview-text:${colors.text};--preview-muted:${colors.muted}`;qs('strong',preview).textContent=appearanceForm.elements.businessName.value||'Sua Marca'}
Object.keys(pinkTheme).filter(key=>key!=='line').forEach(key=>{const picker=appearanceForm.elements[key],hex=appearanceForm.elements[`${key}Hex`];picker.addEventListener('input',()=>{hex.value=picker.value;updateThemePreview()});hex.addEventListener('input',()=>{if(/^#[0-9a-f]{6}$/i.test(hex.value)){picker.value=hex.value;updateThemePreview()}})});appearanceForm.elements.businessName.addEventListener('input',updateThemePreview);
qs('[data-reset-theme]').addEventListener('click',()=>{Object.keys(pinkTheme).filter(key=>key!=='line').forEach(key=>{appearanceForm.elements[key].value=pinkTheme[key];appearanceForm.elements[`${key}Hex`].value=pinkTheme[key]});updateThemePreview()});
appearanceForm.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const colors={...state.config.theme?.colors};Object.keys(pinkTheme).filter(key=>key!=='line').forEach(key=>colors[key]=appearanceForm.elements[key].value);colors.line=colors.line||pinkTheme.line;state.config.business={...state.config.business,name:appearanceForm.elements.businessName.value.trim(),type:appearanceForm.elements.businessType.value.trim(),description:appearanceForm.elements.businessDescription.value.trim()};state.config.theme={...state.config.theme,colors};if(!state.demo){const {doc,setDoc}=state.ctx.firestoreSdk;await setDoc(doc(state.ctx.db,'stores',state.ctx.storeId),{business:state.config.business,theme:state.config.theme},{merge:true})}qs('[data-admin-store-name]').textContent=state.config.business.name;message(qs('[data-appearance-message]'),'Aparência salva com sucesso.',true)}catch(error){message(qs('[data-appearance-message]'),`Não foi possível salvar: ${error.message}`)}finally{button.disabled=false}});

function socialUrl(type){return state.config.contact?.socials?.find(item=>item.label?.toLowerCase().includes(type))?.url||''}
function updateServicePreview(){const delivery=serviceForm.elements.deliveryTime.value.trim()||'—';const pickup=serviceForm.elements.pickupTime.value.trim()||'—';qs('[data-service-preview]').textContent=`Entrega: ${delivery} | Retirada: ${pickup}`}
function fillService(){const service=state.config.service||{};const delivery=state.config.fulfillment?.deliveryMethods?.find(method=>method.id==='delivery')||{};const estimate=service.estimate||'';serviceForm.elements.deliveryTime.value=service.deliveryTime||estimate.match(/Entrega:\s*([^|]+)/i)?.[1]?.trim()||'40–50min';serviceForm.elements.pickupTime.value=service.pickupTime||estimate.match(/Retirada:\s*(.+)$/i)?.[1]?.trim()||'20min';serviceForm.elements.deliveryFee.value=Number(delivery.fee)||0;serviceForm.elements.address.value=state.config.business?.address||'';serviceForm.elements.mapEmbedUrl.value=service.mapEmbedUrl||'';serviceForm.elements.instagram.value=socialUrl('instagram');serviceForm.elements.facebook.value=socialUrl('facebook');const hours=service.hours||[];qs('[data-hours-editor]').innerHTML=weekDays.map((day,index)=>`<label><span>${day}</span><input name="hour-${index}" value="${hours.find(item=>item.day===day)?.time||'Fechado'}" placeholder="Ex.: 08:00–18:00"></label>`).join('');updateServicePreview()}
serviceForm.elements.deliveryTime.addEventListener('input',updateServicePreview);serviceForm.elements.pickupTime.addEventListener('input',updateServicePreview);
serviceForm.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;message(qs('[data-service-message]'));try{const deliveryTime=serviceForm.elements.deliveryTime.value.trim();const pickupTime=serviceForm.elements.pickupTime.value.trim();const hours=weekDays.map((day,index)=>({day,time:serviceForm.elements[`hour-${index}`].value.trim()||'Fechado'}));const service={...state.config.service,deliveryTime,pickupTime,estimate:`Entrega: ${deliveryTime} | Retirada: ${pickupTime}`,hours,mapEmbedUrl:serviceForm.elements.mapEmbedUrl.value.trim()};const business={...state.config.business,address:serviceForm.elements.address.value.trim()};const socials=[...(state.config.contact?.socials||[])];const setSocial=(label,url)=>{const index=socials.findIndex(item=>item.label?.toLowerCase().includes(label.toLowerCase()));const entry={label:`Seu ${label}`,url};if(index>=0)socials[index]={...socials[index],url};else socials.push(entry)};setSocial('Instagram',serviceForm.elements.instagram.value.trim());setSocial('Facebook',serviceForm.elements.facebook.value.trim());const contact={...state.config.contact,socials};const deliveryMethods=(state.config.fulfillment?.deliveryMethods||[]).map(method=>method.id==='delivery'?{...method,fee:Number(serviceForm.elements.deliveryFee.value)||0}:method);const fulfillment={...state.config.fulfillment,deliveryMethods};state.config={...state.config,service,business,contact,fulfillment};if(!state.demo){const {doc,setDoc}=state.ctx.firestoreSdk;await setDoc(doc(state.ctx.db,'stores',state.ctx.storeId),{service,business,contact,fulfillment},{merge:true})}message(qs('[data-service-message]'),'Informações de atendimento salvas com sucesso.',true)}catch(error){message(qs('[data-service-message]'),`Não foi possível salvar: ${error.message}`)}finally{button.disabled=false}});

function showDashboard(){show(dashboard);qs('[data-mode-label]').textContent=state.demo?'Modo demonstração · alterações não são salvas':'Conectado ao Firebase';qs('[data-admin-store-name]').textContent=state.config.business.name;qs('[data-store-open]').checked=state.config.business.open!==false;qs('[data-store-status]').textContent=state.config.business.open!==false?'Aberto':'Fechado';const note=qs('[data-import-note]');note.hidden=state.demo||(!state.needsCatalogUpgrade&&state.products.length>0);if(!note.hidden){qs('p',note).textContent=state.products.length?'Ative a gestão de categorias e a ordenação no catálogo atual.':'O Firestore está vazio. Importe o catálogo atual para começar.';qs('[data-import]',note).textContent=state.products.length?'Ativar gestão completa':'Importar catálogo inicial'}populateCategoryControls();renderProducts();renderCategories();fillAppearance();fillService()}
async function importInitialCatalog(){const button=qs('[data-import]');button.disabled=true;try{const [localProducts,localCategories]=await Promise.all(['../data/products.json','../data/categories.json'].map(url=>fetch(url,{cache:'no-store'}).then(r=>r.json())));const {doc,setDoc,writeBatch}=state.ctx.firestoreSdk;await setDoc(doc(state.ctx.db,'stores',state.ctx.storeId),state.config,{merge:true});const batch=writeBatch(state.ctx.db);const sourceProducts=state.products.length?state.products:localProducts;sourceProducts.forEach((product,index)=>batch.set(doc(state.ctx.db,'stores',state.ctx.storeId,'products',product.id),{...product,order:product.order??index},{merge:true}));state.categories.forEach((category,index)=>batch.set(doc(state.ctx.db,'stores',state.ctx.storeId,'categories',category.id),{...category,order:category.order??index},{merge:true}));await batch.commit();state.products=sourceProducts.map((p,i)=>({...p,order:p.order??i}));state.categories=state.categories.map((c,i)=>({...c,order:c.order??i}));state.needsCatalogUpgrade=false;qs('[data-import-note]').hidden=true;showDashboard()}catch(error){alert(`Falha na ativação: ${error.message}`)}finally{button.disabled=false}}
async function loadFirebaseData(){const {doc,getDoc,collection,getDocs}=state.ctx.firestoreSdk;const [storeDoc,productsDocs,categoriesDocs]=await Promise.all([getDoc(doc(state.ctx.db,'stores',state.ctx.storeId)),getDocs(collection(state.ctx.db,'stores',state.ctx.storeId,'products')),getDocs(collection(state.ctx.db,'stores',state.ctx.storeId,'categories')).catch(()=>null)]);if(storeDoc.exists()){const remote=storeDoc.data();state.config={...state.config,...remote,business:{...state.config.business,...(remote.business||{})},service:{...state.config.service,...(remote.service||{})},contact:{...state.config.contact,...(remote.contact||{})},fulfillment:{...state.config.fulfillment,...(remote.fulfillment||{}),deliveryMethods:remote.fulfillment?.deliveryMethods||state.config.fulfillment.deliveryMethods,paymentMethods:remote.fulfillment?.paymentMethods||state.config.fulfillment.paymentMethods},theme:{...state.config.theme,...(remote.theme||{}),colors:{...state.config.theme.colors,...(remote.theme?.colors||{})}}}}const missingProductOrder=productsDocs.docs.some(item=>item.data().order==null);state.products=productsDocs.docs.map((item,index)=>({id:item.id,order:index,...item.data()})).sort(byOrder);if(categoriesDocs&&!categoriesDocs.empty)state.categories=categoriesDocs.docs.map((item,index)=>({id:item.id,order:index,...item.data()})).sort(byOrder);state.needsCatalogUpgrade=!categoriesDocs||categoriesDocs.empty||missingProductOrder;showDashboard()}

qs('[data-login-form]').addEventListener('submit',async event=>{event.preventDefault();message(qs('[data-login-message]'));try{await state.ctx.authSdk.signInWithEmailAndPassword(state.ctx.auth,event.target.email.value,event.target.password.value)}catch{message(qs('[data-login-message]'),'E-mail ou senha inválidos.')}});
async function authorize(user){const {doc,getDoc}=state.ctx.firestoreSdk;const admin=await getDoc(doc(state.ctx.db,'admins',user.uid));if(!admin.exists()){await state.ctx.authSdk.signOut(state.ctx.auth);message(qs('[data-login-message]'),'Este usuário não possui permissão administrativa.');show(login);return}await loadFirebaseData()}

qsa('[data-admin-tab]').forEach(button=>button.addEventListener('click',()=>{qsa('[data-admin-tab]').forEach(item=>item.classList.toggle('active',item===button));qsa('[data-admin-panel]').forEach(panel=>panel.hidden=panel.dataset.adminPanel!==button.dataset.adminTab)}));
qs('[data-product-search]').addEventListener('input',renderProducts);qs('[data-category-filter]').addEventListener('change',renderProducts);qs('[data-demo]').addEventListener('click',()=>{state.demo=true;showDashboard()});qs('[data-new-product]').addEventListener('click',()=>openProductEditor());qs('[data-new-category]').addEventListener('click',()=>openCategoryEditor());qsa('[data-close-product]').forEach(button=>button.addEventListener('click',()=>productEditor.close()));qsa('[data-close-category]').forEach(button=>button.addEventListener('click',()=>categoryEditor.close()));qs('[data-add-variant]').addEventListener('click',()=>qs('[data-variant-rows]').append(variantRow()));qs('[data-import]').addEventListener('click',importInitialCatalog);qs('[data-logout]').addEventListener('click',async()=>{if(state.demo){location.reload();return}await state.ctx.authSdk.signOut(state.ctx.auth)});

async function bootstrap(){await loadLocal();if(!isFirebaseConfigured()){show(setup);return}state.ctx=await getFirebaseContext();state.ctx.authSdk.onAuthStateChanged(state.ctx.auth,user=>{if(user)authorize(user).catch(error=>{message(qs('[data-login-message]'),error.message);show(login)});else show(login)})}
bootstrap().catch(error=>{setup.hidden=false;setup.querySelector('p').textContent=`Não foi possível iniciar o painel: ${error.message}`});

